<a href="https://colab.research.google.com/github/novandoquiro/Ovando-Lab-Reports/blob/main/Nicolas_Ovando_Final_Copy_of_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [ ]:
for i in range(100):
    print(i)

In [131]:
# here we are setting the range to 100 so we will get a numbered list from 0-99 which results in one hundred numbers

In [52]:
for i in range(5,8):
    print(i)

5
6
7


In [133]:
# here we are just printing the numbers in between 5 and 8 but not the number eight because for that we would need to change the range to (5,9) to include the 8

In [53]:
for i in range(3):
    print( "Test Number: " , i )

Test Number:  0
Test Number:  1
Test Number:  2


In [134]:
# here we are again printing a range of numbers but this time we are including the text "test number:" before each one

### Functions

In [135]:
def square(x):
    return x**2

In [136]:
# this is the code to square any number as x

In [55]:
square(5)

25

In [137]:
# in this case x is 5 so the code is squaring 5 which results in 25

In [56]:
square(square(2))

16

In [138]:
# here we are squaring the square of 2 which means we fist square 2 and then square the result of that

In [57]:
square(square(square(2)))


256

In [139]:
# similar to the previous code here the code is squaring three times instead of two 

In [58]:
square(123456)

15241383936

In [140]:
# this is just an example of a big random number being squared

In [59]:
square(square(5))

625

In [60]:
def add_two(x):
    return x+2

In [141]:
# this is the code to add 2 to any number set as x 

In [61]:
add_two(5)

7

In [142]:
# here x is 5 so the code is adding 2 to 5 which is 7

In [62]:
square(add_two(5))

49

In [143]:
# here we combined both codes to add and square at the same time

### Logical Branching

In [63]:
choice = "apple"

In [64]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You choose apples.


In [145]:
# here we just set our choice as apple and then gave the instruction to print the result "you choose apples" if my choice is apple or "you did not choose apples" if its not my choice

In [65]:
choice = "orange"

In [66]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


In [146]:
# since I chose orange instead of apple the printed result is "you did not choose apples"

In [67]:
choice = "apple"

In [68]:
if choice == "apple":

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


In [147]:
# for this code we just added a couple of other texts to appear on the result based on our choice

### User Input

In [69]:
choice = input("Please enter your choice (i.e. apple): ")

Please enter your choice (i.e. apple): apple


In [70]:
choice

'apple'

In [148]:
# here I just inputed my choice as apple

In [71]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You choose apples.


In [149]:
# again, this code is stating to print specific texts as my result based on the choice I pick

#### Coins

In [72]:
import numpy as np
import matplotlib.pyplot as plt

In [73]:
np.random.random()

0.8550213706090604

In [150]:
# this is just a random number we printed

In [74]:
np.random.random() > 0.5

False

In [151]:
# here we created a code to identify if the random number is greater than 0.5 

In [75]:
def flip_coin():
    if np.random.random() > 0.5:
        print("Heads")
    else:
        print("Tails")

In [152]:
# in this case we are now telling colab to print "heads" if the number is greater than 0.5 or "tails" if its less than that

In [76]:
flip_coin()

Tails


In [153]:
# here we just flipped the coin to see our result 

### Graphics Output

In [77]:
from IPython.core.display import display, HTML

In [78]:
display(HTML('<h1>Hello, world!</h1>'))

In [154]:
# here we are telling colab to display what is inside of the html

In [79]:
def coin():
  return np.random.randint(2)

In [80]:
coin()

1

In [81]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">'))

In [155]:
# this is an example of displaying an imgage from the url inside the html

In [82]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg'

In [83]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [84]:
show_img(heads)

In [158]:
# this is displaying the image of the heads coin url

In [85]:
show_img(tails)

In [159]:
# this is displaying the image of the tails url

In [86]:
def flip_coin():

    if coin():
        show_img(heads)
    else:
        show_img(tails)

In [87]:
flip_coin()

In [160]:
# here we are flipping the coin at random to see if our results is either heads or tails

In [88]:
for i in range(5):
    flip_coin()

In [161]:
# here we are flipping the coin five times and getting the result as an image for each one

In [89]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

### Cards

In [90]:
def shuffle(x):
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [162]:
# here we created a code to shuffle the range 

In [91]:
a = np.arange(52)

In [163]:
# here we are setting our range of numbers from 0-51

In [92]:
shuffle(a)

array([ 3, 17, 32, 50, 23, 43, 48, 29,  5, 35, 42, 18, 39, 38, 33, 24, 49,
       45, 28, 25, 14, 19, 15,  9, 13,  0, 20, 51,  6, 22, 12, 30, 21,  8,
       16, 11,  2, 37, 47, 36,  4, 44, 46, 10, 31, 34,  7,  1, 41, 26, 27,
       40])

In [164]:
# now we shuffled the numbers in the list

In [93]:
np.random.permutation(52)

array([18,  3, 30,  1, 39, 45, 41, 44, 48, 28, 17, 46, 15, 34,  8, 31, 38,
       40,  0,  4, 23, 29, 12, 50, 35, 13, 24, 20,  9, 26, 42,  7, 14, 51,
       21, 25, 33, 16, 47, 27,  2,  6, 11, 37, 49, 32, 22, 43, 36, 19,  5,
       10])

### Speed Test

In [94]:
%%timeit
shuffle(a)

182 µs ± 2.04 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [95]:
%%timeit
np.random.permutation(52)

3.3 µs ± 63.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [165]:
# for these two codes im not sure what we are exactly doing

In [96]:
import numpy as np

In [97]:
np.random.permutation(52)

array([28,  1, 35, 31, 19, 50, 34, 49, 18, 26, 36, 14, 51, 24, 22, 43,  2,
       42, 48, 27, 12, 47, 45, 39,  7,  9, 37, 29,  3, 21, 20, 23, 15, 38,
       41, 11,  6, 16,  8, 30, 13, 32, 25,  0,  4,  5, 46, 17, 10, 33, 44,
       40])

In [166]:
# this is again just arranging the order of the numbers randomly 

In [98]:
cards = np.random.permutation(52)

In [167]:
# here we are setting the shuffle code for the 52 numbers equal to cards

In [99]:
cards

array([30, 43,  7, 47, 10, 36, 28, 41, 29, 14, 22, 24, 31, 32, 25, 34, 51,
       44,  5, 45, 37, 17, 49,  4, 11,  8, 27,  9, 35, 16, 18, 42,  2,  3,
        0, 48, 50, 13, 19, 40,  1, 38,  6, 21, 26, 12, 46, 33, 23, 39, 15,
       20])

In [169]:
# if we plot now plot "cards" we get the a shuffled order of the 52 numbers

In [100]:
cards[0]

30

In [170]:
# this means our card number zero is the number 30

In [101]:
cards[1]

43

In [172]:
# this means our card first card or number on our list is the number 43

In [102]:
cards[2]

7

In [173]:
# same thing going on here

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [174]:
# this is an image display of our 52 playing cards 

In [103]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [175]:
# here we are organizing our number list in order from 0 to 51

In [104]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [176]:
# here we are organizing our 52 cards in 4 separate rows each going from 0 to 12

In [105]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [106]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [107]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [178]:
# here we are now coding the numbers on our array to represent a specific card in the deck

In [108]:
card_name(0)

'Ace of Clubs'

In [179]:
# this means the fist card of the deck is the ace of clubs

In [109]:
card_name(51)

'King of Diamonds'

In [180]:
# this means the last card in our deck or array is the king of diamonds

In [110]:
cards = np.random.permutation(52)

In [111]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [183]:
# here we are setting the text top, second, and last card in the deck to give us the actual cards in that order from our deck

In [112]:
top_of_deck, second_card_in_deck, last_card_in_deck

('Two of Diamonds', 'Nine of Diamonds', 'Five of Diamonds')

In [113]:
for i in range(5):
    print(card_name(cards[i]))

Two of Diamonds
Nine of Diamonds
Four of Clubs
Five of Clubs
Six of Hearts


In [181]:
# here we are printing the first five cards in the deck 

In [114]:
for i in range(15):
    print(card_name(cards[i]))

Two of Diamonds
Nine of Diamonds
Four of Clubs
Five of Clubs
Six of Hearts
Ten of Spades
Seven of Hearts
Five of Spades
Queen of Spades
Four of Hearts
Ace of Clubs
King of Spades
Ten of Diamonds
Jack of Hearts
Ace of Diamonds


In [182]:
# here we are printing the first 15 cards in the deck

https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [115]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [184]:
# this is just the urls for the cards' head and tail

In [116]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [117]:
i = np.random.randint(4)
j = np.random.randint(13)

In [118]:
i,j

(1, 6)

In [119]:
suit[i]

'p'

In [120]:
card[j]

'7'

In [121]:
from IPython.core.display import display, HTML

In [122]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [185]:
# this is the same code we have been using before to display an image from a html url

In [123]:
img = card_url_head + suit[i] + card[j] + card_url_tail

In [124]:
show_img(img)

In [187]:
# this is a card image displayed

In [125]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [192]:
# here we are printing the card image with its card number instead

In [126]:
card_image(3)

'k4'

In [127]:
img = card_url_head + card_image(3) + card_url_tail

In [128]:
show_img(img)

In [191]:
# here the code is showing us what card number 3 in the deck looks like

In [ ]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)

In [190]:
# here we are printing an image of each card in the deck in order from least to greatest and grouped by its card symbol