<a href="https://colab.research.google.com/github/novandoquiro/Ovando-Lab-Reports/blob/main/OvandoLab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Stats notebook lab 3 

In [1]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [2]:
for i in range(5,8):
  print(i)

5
6
7


In [3]:
for i in range(3):
  print( "Test Number: " , i )

Test Number:  0
Test Number:  1
Test Number:  2


#Functions

In [4]:
def square(x):
  return x**2

In [5]:
square(5)

25

In [6]:
square(6)

36

In [7]:
square(123456)

15241383936

In [8]:
square(square(5))

625

In [9]:
square(square(square(2)))

256

In [10]:
def add_two(x):
  return x+2

In [11]:
add_two(5)

7

In [12]:
square(add_two(5))

49

In [13]:
choice = "apple"

In [14]:
if choice == "apple":

    print("You choose apples.")

else:

    print("You did not choose apples.")

You choose apples.


In [15]:
if choice == "apple":

    print("You choose apples.")

elif choice == "orange":

    print("You choose oranges.")

else:

    print("You did not choose apples or oranges.")

You choose apples.


In [16]:
if choice == "apple":

    print("You choose apples.")
    print("Thank you, shop again!")

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")
else:

    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!


#User Input 

In [17]:
choice = input("Please enter your choice (i.e. apple): ")

Please enter your choice (i.e. apple): orange


In [18]:
choice

'orange'

In [19]:
import numpy as np

In [20]:
np.random.permutation(52)

array([50, 29, 18, 25, 13, 15, 11,  8, 47, 44,  4, 49,  6, 38, 33,  5, 20,
       36, 27, 23, 30, 24, 31,  3, 46,  0, 21,  1, 41, 42, 28, 43, 35, 51,
       12, 40, 16, 17, 10, 34,  9, 19, 14, 37, 48,  7, 45,  2, 39, 22, 32,
       26])

In [21]:
cards = np.random.permutation(52)

In [22]:
cards

array([42, 45, 12, 28,  3, 33,  4, 46, 30, 43, 47, 26, 38, 39, 34, 36, 51,
       32,  9, 20,  7,  2,  6, 31, 11, 44, 40, 23, 35, 10, 22, 13, 50,  8,
        0, 25, 49, 14, 16, 27, 37, 21,  1, 15, 19, 17, 24, 41, 18, 48,  5,
       29])

In [23]:
cards[0]

42

In [24]:
cards[1]

45

In [25]:
cards[2]

12

<img src= 'http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [26]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [27]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [28]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [29]:
suits = ['Clubs', 'Spades', 'Hearts', 'Diamonds']
names = ['Ace', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten', 'Jack', 'Queen', 'King']

In [30]:
suits

['Clubs', 'Spades', 'Hearts', 'Diamonds']

In [31]:
suits[0]

'Clubs'

In [32]:
names[1]

'Two'

In [33]:
def card_name(card_number):

    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [34]:
card_name(0)

'Ace of Clubs'

In [35]:
card_name(1)

'Two of Clubs'

In [36]:
card_name(51)

'King of Diamonds'

In [37]:
card_name(23)

'Jack of Spades'

In [38]:
cards = np.random.permutation(52)

In [39]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [40]:
top_of_deck,second_card_in_deck,last_card_in_deck

('Jack of Diamonds', 'Two of Clubs', 'Five of Spades')

In [41]:
for i in range(5):
    print(card_name(cards[i]))

Jack of Diamonds
Two of Clubs
Two of Diamonds
King of Clubs
Six of Clubs


In [42]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [43]:
suit = ['k', 'p', 's', 'l']
card = ['a', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'j', 'q', 'k']

In [44]:
i = np.random.randint(4)
j = np.random.randint(13)

In [45]:
i,j

(3, 6)

In [46]:
suit[i]

'l'

In [47]:
card[j]

'7'

In [48]:
from IPython.core.display import display, HTML

In [49]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [50]:
img = card_url_head + suit[i]+card[j] + card_url_tail

In [51]:
show_img(img)